/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
	// By default, Docusaurus generates a sidebar from the docs folder structure
	// tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
	mainSidebar: [
		{
			type: 'category',
			label: 'Getting started',
			items: ['introduction'],
		},
		{
			type: 'category',
			label: 'Directives',
			items: ['directives/in-view'],
		},
		{
			type: 'category',
			label: 'Pipes',
			items: ['pipes/enum-property'],
		},
		{
			type: 'category',
			label: 'Services',
			items: ['services/environment-variables'],
		},
		{
			type: 'category',
			label: 'Animations',
			items: ['animations/animations'],
		},
		{
			type: 'category',
			label: 'Utilities',
			items: ['utilities/loading-state', 'utilities/route-config-loading', 'utilities/table-state'],
		},
		{
			type: 'category',
			label: 'Testing',
			items: ['testing/extract-public', 'testing/async-data', 'testing/async-error'],
		},
	],

	// But you can create a sidebar manually
	/*
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Tutorial',
      items: ['hello'],
    },
  ],
   */
};

module.exports = sidebars;
