minimumReleaseAge: 28800

overrides:
  ajv@>=8.0.0 <8.18.0: '>=8.18.0'
  esbuild@<0.28.1: '>=0.28.1'
  koa@<3.1.2: '>=3.1.2'
  minimatch@<7.4.8: '>=7.4.8'
  qs@<6.15.2: '>=6.15.2'
  uuid@<11.1.1: '>=11.1.1'
  webpack-dev-server@<5.2.4: '>=5.2.4'
  ws@<8.20.1: '>=8.20.1'
  tmp@>=0.2.6 <0.2.7: '>=0.2.7'
  form-data@>=4.0.0 <4.0.6: '>=4.0.6'
  tar@<=7.5.15: '>=7.5.16'
  launch-editor@<=2.14.0: '>=2.14.1'
  js-yaml@<=4.1.1: '>=4.2.0'
  '@babel/core@<=7.29.0': '>=7.29.6'
  http-proxy-middleware@>=3.0.4 <3.0.7: '>=3.0.7'
  undici@>=7.23.0 <7.28.0: '>=7.28.0'
  undici@>=7.0.0 <7.28.0: '>=7.28.0'
  undici@<6.27.0: '>=6.27.0'
  http-proxy-middleware@>=0.16.0 <2.0.10: '>=2.0.10'
  http-proxy-middleware@>=3.0.0 <3.0.6: '>=3.0.6'
  '@sigstore/core@<=3.2.0': '>=3.2.1'
