name: Docs

on:
  push:
    branches:
      - main
      - 'issue-14-improve-documentation'

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Setup git
        run: |
          git config --global user.name "${{ secrets.USER_NAME }}"
          git config --global user.email "${{ secrets.USER_EMAIL }}"
          echo "machine github.com login ${{ secrets.USER_NAME }} password ${{ secrets.ACCESS_TOKEN }}" > ~/.netrc

      - name: Run & deploy
        run: |
          cd website
          npm ci
          GIT_USER="${{ secrets.USER_NAME }}" npm run deploy
